"""create books and authors

Revision ID: e6ec097c4a55
Revises: 78fc9248b86c
Create Date: 2023-06-29 15:27:47.429685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ec097c4a55'
down_revision = '78fc9248b86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
